### DISCUSSION TITLE
Retrying connection to database instance

### DISCUSSION THREAD

**Discussion by linus-jansson** [medusajs/medusa#4787] [Feature Requests]
Hello!

I am trying medusa out with nextjs and postgresql using docker. See below for a insight on my docker compose file.

However, it seems like the backend (medusa) starts before the postgresql container. Resulting in medusa spitting out an error saying it cant connect to the databse. From the CLI output it also seems like medusa doesn't try to reconnect but just continues on. Is this purposely done?

Wouldn't it be better to try to reconnect for some time and then crash as medusa depends on the database?

Please correct me if my assumptions are wrong as I am just a couple of hours in to my medusa adventure.

Cheers :)

```
version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: "store-frontend/Dockerfile" 
    restart: unless-stopped
    ports: 
      - "8000:8000"
  backend:
    build:
      context: .
      dockerfile: "store-backend/Dockerfile" 
    depends-on: 
      - database
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_URL=postgres://postgres:qwerty123456@localhost/medusa--sNB
    restart: unless-stopped
    ports: 
      - "7001:7001"
      - "9000:9000"
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwerty123456
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
```
