### DISCUSSION TITLE
Is medusa production ready ecommerce solution?

### DISCUSSION THREAD

**Discussion by nparoski** [medusajs/medusa#5121] [Q&A]
Hello, I've been playing around with medusajs and It seems like it's too buggy to be able to run in real world.
I've followed latest setup guide and created docker configuration for backend

**Dockerfile**
```
FROM node:18.17.1

COPY . /app
WORKDIR /app
RUN npm cache clean --force
RUN npm install

CMD ["npm","run","dev"]
```
**docker-compose.yml**
```
version: "3.8"

services:
  backend:
    container_name: api_backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "7001:7001"
      - "7000:7000"
      - "9000:9000"
    depends_on:
      - database

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medusa_db
```

1. Can't add item to cart randomly

**Request**
```
Request URL:
http://localhost:9000/store/carts/cart_01HAMHP51F21P6XCJ7KM0K5N7Z/line-items
Request Method:
POST
Status Code:
500 Internal Server Error
Remote Address:
[::1]:9000
Referrer Policy:
strict-origin-when-cross-origin
```
**Payload**
```
{code: "unknown_error", type: "unknown_error", message: "An unknown error occurred."}
```

2. Created product and when I want to add another variant I get error

![image](https://github.com/medusajs/medusa/assets/35550355/b12fbf49-cfe2-4084-9ece-7b6a5d738e29)
