### ISSUE TITLE
[Bug]: Widgets not shown on deployed docker image

### ISSUE THREAD

**Issue by mikkel-lindstrom** [medusajs/medusa#11420]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@azure/storage-blob": "^12.26.0",
    "@medusajs/admin-sdk": "2.4.0",
    "@medusajs/cli": "2.4.0",
    "@medusajs/framework": "2.4.0",
    "@medusajs/medusa": "2.4.0",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "@tiptap/extension-color": "^2.11.5",
    "@tiptap/pm": "^2.11.5",
    "@tiptap/react": "^2.11.5",
    "@tiptap/starter-kit": "^2.11.5",
    "awilix": "^8.0.1",
    "pg": "^8.13.0",
    "soap": "^1.1.7"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.4.0",
    "@mikro-orm/cli": "6.4.3",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  },
  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
}
```

### Node.js version

20.9.0-alpine

### Database and its version

PostgreSQL 16.4

### Operating system name and version

Linux / Azure web app

### What happended?

Widgets are not being rendered when running from a the docker image, we can see in the docker image that the widgets code are to be found in "medusa-app/public/admin/assets/index-*.js"

They are defined as arrow functions and they have a zone indication with double quotes.

Running with 
DISABLE_MEDUSA_ADMIN=false
MEDUSA_WORKER_MODE=shared
and relevant CORS settings

Dockerfile:
```
FROM node:20.9.0-alpine
RUN mkdir /medusa-app
WORKDIR /medusa-app
COPY . .
RUN chmod 777 entrypoint.sh
RUN yarn install
EXPOSE 9000
CMD [ "yarn","start" ]
```

relevant pipeline steps:

```
variables:
     dockerfilePath: 'build/Dockerfile-backend-dev'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
- script: |
    cd droemmeland
    yarn install
  displayName: 'yarn install'

- script: |
    cd droemmeland
    yarn build
  displayName: 'yarn build'
  
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/droemmeland/.medusa/server'
    contents: |
       **
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy output files'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/build'
    contents: |
       entrypoint.sh
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy entrypoint for docker'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/droemmeland'
    contents: |
       .end.dev
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy .env file for development'
```

### Expected behavior

Widgets are also being rendered in deployed and builded version

### Actual behavior

Nothing is rendered in the DOM, no errors in console or network calls

### Link to reproduction repo

_
