### ISSUE TITLE
[Bug]: Price lists are not applied if the same customer is attached to two different customer groups

### ISSUE THREAD

**Issue by docloulou** [medusajs/medusa#11875]
### Package.json file

```JSON
2.6.1 fresh starter
```

### Node.js version

v21

### Database and its version

supabase

### Operating system name and version

linux

### Browser name

chrome

### What happended?

Hello,

```
Setup:

- 1 customer
- 2 groups
- 2 price lists:
  - A: **with** customer group rule
  - B: **without** customer group rule (global price list with prices lower than A)
```

When a customer belongs to **2 different groups**, price lists **with a customer group rule** are not applied:
- Price List A is **not applied**
- Price List B is **applied**

When a customer belongs to **1 group**:
- Price List A is **applied**
- Price List B is **not applied**, even if its prices are lower

**Demo:** [https://jam.dev/c/cc9cd393-288c-4d3d-a3b3-f082f56340f2](https://jam.dev/c/cc9cd393-288c-4d3d-a3b3-f082f56340f2)

### Expected behavior

- Even if the customer is attached to more than one customer group, the PL **with the customer group rule** should be applied.
- According to rules, the PL with lower prices should applied

### Actual behavior

- If the customer is attached to more than one customer group, all PL **with customer group rule** are ignored.
- If the customer is attached to only one customer group, only PL **with customer group rule** are applied, and all other PL **without customer group rule** are ignored, **even if the price is lower**.

### Link to reproduction repo

https://jam.dev/c/cc9cd393-288c-4d3d-a3b3-f082f56340f2
