### ISSUE TITLE
Can't create product variant

### ISSUE THREAD

**Issue by nparoski** [medusajs/medusa#5122]
### Describe the bug

1. Login as admin
2. Create product
3. Add variant with name "blue"
4. Error, product "green" exists
5. Check screenshots

### System information

Medusa version (including plugins):
```
"@medusajs/admin": "^7.0.1",
"@medusajs/cache-inmemory": "^1.8.8",
"@medusajs/cache-redis": "^1.8.8",
"@medusajs/event-bus-local": "^1.9.6",
"@medusajs/event-bus-redis": "^1.8.9",
"@medusajs/file-local": "^1.0.2",
"@medusajs/icons": "^1.0.0",
"@medusajs/medusa": "^1.15.0",
"@medusajs/ui": "^1.0.0",
"@medusajs/medusa-cli": "^1.3.16"
```
Node.js version: 18.17.1
Database: Postgre 15.4
Operating system: Windows
Browser (if relevant): Chrome

### Steps to reproduce the behavior

6. Scroll down to '....'
7. See error

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots
![image](https://github.com/medusajs/medusa/assets/35550355/3086197c-44ac-44b7-b80b-63f76de080e2)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context
**Dockerfile**
```
FROM node:18.17.1

COPY . /app
WORKDIR /app
RUN npm cache clean --force
RUN npm install

CMD ["npm","run","dev"]
```
**docker-compose.yml**
```
version: "3.8"

services:
  backend:
    container_name: api_backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "7001:7001"
      - "7000:7000"
      - "9000:9000"
    depends_on:
      - database

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medusa_db
```
