### ISSUE TITLE
Can't add product to cart

### ISSUE THREAD

**Issue by nparoski** [medusajs/medusa#5124]
### Describe the bug
Clicking add to cart doesn't do anything, checking dev console I can see error 500
### System information

Medusa version (including plugins):
```
"@medusajs/admin": "^7.0.1",
"@medusajs/cache-inmemory": "^1.8.8",
"@medusajs/cache-redis": "^1.8.8",
"@medusajs/event-bus-local": "^1.9.6",
"@medusajs/event-bus-redis": "^1.8.9",
"@medusajs/file-local": "^1.0.2",
"@medusajs/icons": "^1.0.0",
"@medusajs/medusa": "^1.15.0",
"@medusajs/ui": "^1.0.0",
"@medusajs/medusa-cli": "^1.3.16"
```
Node.js version: 18.17.1
Database: Postgre 15.4
Operating system: Windows
Browser (if relevant): Chrome

### Steps to reproduce the behavior
1. Go to store
2. Click on any product (only medusa t-shirt worked)
3. Click add to cart

**Request**
```
Request URL:
http://localhost:9000/store/carts/cart_01HAMHP51F21P6XCJ7KM0K5N7Z/line-items
Request Method:
POST
Status Code:
500 Internal Server Error
Remote Address:
[::1]:9000
Referrer Policy:
strict-origin-when-cross-origin
```
**Payload**
```
{code: "unknown_error", type: "unknown_error", message: "An unknown error occurred."}
```
### Additional context
**Dockerfile**
```
FROM node:18.17.1

COPY . /app
WORKDIR /app
RUN npm cache clean --force
RUN npm install

CMD ["npm","run","dev"]
```
**docker-compose.yml**
```
version: "3.8"

services:
  backend:
    container_name: api_backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "7001:7001"
      - "7000:7000"
      - "9000:9000"
    depends_on:
      - database

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medusa_db
```
