### ISSUE TITLE
Not able to use Medusa with Docker Compose

### ISSUE THREAD

**Issue by manikmi** [medusajs/medusa#5564]
### Describe the bug
Hi Folks,

I am trying to setup docker compose environment with Medusa.

1. Postgres v15
2. Medusa Adi with API
3. Medusa  Storefront (the one comes which initializing Medusa)
4. nginx
While setting the env up, I am able to setup connections using the Docker compose

The product details page is not showing up in the storefront.

### System information

Medusa version (including plugins): v1.3.21
Node.js version: 18
Database: Postgres v 15
Operating system: Mac
Browser (if relevant):

### Expected behavior

The product details should show up

### Screenshots
<img width="837" alt="image" src="https://github.com/medusajs/medusa/assets/797398/053072ce-4af5-4d13-84c5-b247a1068398">

<img width="827" alt="image" src="https://github.com/medusajs/medusa/assets/797398/7cf726c6-a337-4b42-8a54-4bca9edcc6d1">

### Code snippets

Docker Compose
```
version: '3.8'

services:

  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: <some-password>
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data

  admin:
    build: ./my-medusa-store
    command: npm run dev
    restart: always
    depends_on:
      - db
    links:
      - "db:database"
    ports:
      - 7001:7001
      - 9000:9000
    volumes:
      - ./my-medusa-store-storefront:/my-medusa-store-storefront
    

  storefront:
    build: ./my-medusa-store-storefront
    # image: storefront
    command: npm run start
    restart: always
    volumes:
      - ./my-medusa-store-storefront:/app
    depends_on:
      - admin
    links:
      - "db:database"
      - "admin:admin"
    ports:
      - 8000:8000
    environment:
      NODE_ENV: development

  webserver:
    image: nginx
    restart: always
    ports:
      - 80:80
    links:
      - "admin:admin"
      - "storefront:storefront"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
      - admin
      - storefront
```

I have created Docker for Storefront like this:

```
FROM node:18-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
RUN  npm install --production

FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "start"]

```

I have made updates in .env.local in storefront as:

```
NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://localhost/adminapi
NEXT_PUBLIC_BASE_URL=http://localhost/adminapi
POSTGRES_URL=postgres://postgres:postgres@database:5432/medusa
```

The sample data is seeded into the platform. 
The initial load of the storefront is loading fine. But it fails as I click on any product to load details with the following error.
```
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 193452068
```
Could not find the logs to support this.
Any help is deeply appreciated.
Add any other context about the problem here

**Comment by manikmi** [comment]
Can somebody please lend a hand on this issue?

**Comment by sankalpsingha** [comment]
This is an issue, I am also not able to run medusa in docker compose and the example that they have is pretty old. It would be great if there is some example for this.

**Comment by sankalpsingha** [comment]
I have managed to get the standard installation of admin backend running, but I am not able to login, even though the user exists and has been seeded already : 

```
version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile
    image: backend:latest
    container_name: medusa-server
    restart: always
    command: ["npm", "run", "start"]
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      STORE_CORS: http://localhost
      JWT_SECRET: something
      COOKIE_SECRET: something

    volumes:
      - medusa-data:/data
    ports:
      - "8080:9000"

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis
    container_name: cache
    volumes:
      - cache-data:/data
    expose:
      - 6379

volumes:
  medusa-data:
  db-data:
  cache-data:
```
