### ISSUE TITLE
Cannot dockerize and no errors are shown

### ISSUE THREAD

**Issue by raquelhortab** [medusajs/medusa#8076]
Hi, I have spend hours trying to dockerize the app but once I get it running, neither the storefront or the admin front can connect to the back.

this is my docker-compose file:

```
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=/data/postgres
      - POSTGRES_DB=medusa-G5-S
      - PGUSER=${DATABASE_USER}
    volumes:
      - ./db:/data/postgres
      - ./dumps/dumpfile.sql:/docker-entrypoint-initdb.d/init-user-db.sql:ro
    command:
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  front:
    build: geekle_ia_storefront
    ports:
      - "8000:8000"
    environment:
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://back:9000
      - NEXT_PUBLIC_BASE_URL=http://front:8000
    depends_on:
      - backend
  backend:
    build: geekle_ia
    ports:
      - "9000:9000"
      - "7001:7001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - STORE_CORS=*
      - DATABASE_TYPE=postgres
      - DATABASE_NAME=medusa-G5-S
      - MEDUSA_ADMIN_ONBOARDING_TYPE=nextjs
      - MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY=geekle_ia_storefront
```

Neither 8000 not 7001 work, the front fails on a fetch to :9000 but that port is indeed working.

![Screenshot from 2024-07-11 05-04-58](https://github.com/medusajs/medusa/assets/19463905/cf612ff8-ecb5-4acf-b6f6-ad737dbe1063)

All I got in the logs when I try to acces is:
```
geekle_ia-backend-1  | ::ffff:172.20.0.1 - - [11/Jul/2024:02:58:40 +0000] "GET /store/regions HTTP/1.1" 200 47 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
```

I guess is some security or cors thing . 

Depending on whether I make this work, medusajs will be used to start a very big project or something else will.
